CREATE TABLE ADMIN (
    admin_id INT PRIMARY KEY AUTO_INCREMENT, 
    nom VARCHAR(25) NOT NULL,
    prenom VARCHAR(25),
    email VARCHAR(50) CHECK(email LIKE '%@%.%')
) AUTO_INCREMENT=1;


CREATE TABLE PROFS (
    prof_id INT UNIQUE PRIMARY KEY AUTO_INCREMENT, 
    nom VARCHAR(25) NOT NULL,
    prenom VARCHAR(25),
    email VARCHAR(50) CHECK(email LIKE '%@%.%'),
    rôle VARCHAR(20)
) AUTO_INCREMENT=1;


CREATE TABLE ETUDIANTS (
    etudiant_id INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(25) NOT NULL,
    prenom VARCHAR(25),
    email VARCHAR(50) CHECK(email LIKE '%@%.%'),
    classe VARCHAR(20),
    prof_id INT UNIQUE,
    FOREIGN KEY (prof_id) REFERENCES PROFS(prof_id)
) AUTO_INCREMENT=1;


CREATE TABLE QCM (
    qcm_id INT PRIMARY KEY AUTO_INCREMENT,
    path VARCHAR(100),
    prof_id INT UNIQUE NOT NULL,
    FOREIGN KEY (prof_id) REFERENCES PROFS(prof_id)
) AUTO_INCREMENT=1;
