DESCRIBE ADMIN;
DESCRIBE PROFS;
DESCRIBE ETUDIANTS;
DESCRIBE QCM;


DROP TABLE ETUDIANTS;
DROP TABLE ADMIN, PROFS, ETUDIANTS;

DROP VIEW PROFS_SELECT, ETUDIANTS_SELECT;

CREATE VIEW PROFS_SELECT AS ;
SELECT * FROM PROFS;



CREATE VIEW ETUDIANTS_SELECT AS 
SELECT * FROM ETUDIANTS;

DESCRIBE ETUDIANTS_SELECT;