--describe :
DESCRIBE ADMIN;
DESCRIBE PROFS;
DESCRIBE ETUDIANTS;
DESCRIBE QCM;

--drop :
DROP TABLE ETUDIANTS;
DROP TABLE QCM, ADMIN, PROFS, ETUDIANTS;

DROP VIEW PROFS_SELECT, ETUDIANTS_SELECT;

CREATE VIEW PROFS_SELECT AS ;

--select :
SELECT * FROM ADMIN;
SELECT * FROM PROFS;
SELECT * FROM ETUDIANTS;
SELECT * FROM QCM;




--views :
CREATE VIEW ETUDIANTS_SELECT AS 
SELECT * FROM ETUDIANTS;

DESCRIBE ETUDIANTS_SELECT;